### ISSUE TITLE
QR Code tidak muncul di folder public/upload

### ISSUE THREAD

**Issue by Fadh10** [ikhsan3adi/absensi-sekolah-qr-code#10]
Setelah klik generate all guru tidak ada image qr code di folder public/upload

**Comment by ikhsan3adi** [comment]
Solusi:

- Pastikan extension php `intl`dan `gd` sudah diaktifkan (lihat readme)
- Download ulang source code karena baru-baru ini ada perbaikan error. Download zip ulang atau download di link berikut:

https://github.com/ikhsan3adi/absensi-sekolah-qr-code/releases/tag/v1.0.5

**Comment by notandz** [comment]
saya sudah download versi terbaru ttp ndak bisa generate qr nya mas stuck

**Comment by notandz** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/89618518/bc5aedf3-5947-4473-986a-d8232f64f80d)

Tidak jalan loadingnya mas

**Comment by notandz** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/89618518/60ec22e1-e2cf-47d6-8b0f-d63d0c2ac3e4)

artinya apa bang

**Comment by ikhsan3adi** [comment]
> ![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/89618518/60ec22e1-e2cf-47d6-8b0f-d63d0c2ac3e4)
> 
> artinya apa bang

Coba `CI_ENVIRONMENT` ganti ke development di `.env` biar errornya kelihatan

**Comment by notandz** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/89618518/6c2d5c5f-4afe-4f15-af9a-6f8fdb869c71)
Begini dia bang

**Comment by ikhsan3adi** [comment]
Udah development mode itu bang?

**Comment by notandz** [comment]
sudah bang, environtment nya aku ganti ke development
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/89618518/c41fc978-ae95-4661-941c-5d2573e26353)

**Comment by ikhsan3adi** [comment]
![Untitled](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/93766033/b145d570-a461-4d8c-825e-16b1dd8f7531)

Dari yang saya tangkap sih kayanya ada masalah di logonya. Mungkin formatnya tidak sesuai, coba ganti logo lain

**Comment by notandz** [comment]
bagaimana cara menghilangkan logo nya mas

**Comment by ikhsan3adi** [comment]
> bagaimana cara menghilangkan logo nya mas

ganti file `public/assets/img/logo_sekolah.jpg`

kalau belum berhasil coba hilangkan logonya di `app\Controllers\Admin\QRGenerator.php`

```php
      // Create logo
      $this->logo = Logo::create(base_url('public/assets/img/logo_sekolah.jpg'))->setResizeToWidth(75); // hapus ini

      // Save it to a file
      $this->writer
         ->write(qrCode: $this->qrCode, logo: $this->logo, label: $this->label)
         ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
```

jadi:

```php
      // Save it to a file
      $this->writer
         ->write(qrCode: $this->qrCode, label: $this->label)
         ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
```

**Comment by notandz** [comment]
terimakasih banyak mas, sudah berhasil

**Comment by irfandd** [comment]
> > bagaimana cara menghilangkan logo nya mas
> 
> ganti file `public/assets/img/logo_sekolah.jpg`
> 
> kalau belum berhasil coba hilangkan logonya di `app\Controllers\Admin\QRGenerator.php`
> 
> ```
>       // Create logo
>       $this->logo = Logo::create(base_url('public/assets/img/logo_sekolah.jpg'))->setResizeToWidth(75); // hapus ini
> 
>       // Save it to a file
>       $this->writer
>          ->write(qrCode: $this->qrCode, logo: $this->logo, label: $this->label)
>          ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
> ```
> 
> jadi:
> 
> ```
>       // Save it to a file
>       $this->writer
>          ->write(qrCode: $this->qrCode, label: $this->label)
>          ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
> ```

saya udah ngikutin perintah ini + .env sudah development hasilnya msh sama saja pak "internal server error" ketika scan qrcode masuk, untuk composer.json saya pakai "codeigniter4/framework": "4.3.5" dan xampp yang saya gunakan versi 8.1.12

**Comment by watashiyoga** [comment]
> terimakasih banyak mas, sudah berhasil

gmn mas caranya saya sudah coba tidak berhasil kalau baris logo dihilangkan tidak bisa generate, kalau gambarnya diblank putih juga tidak bisa
