### ISSUE TITLE
CodeIgniter\View\Exceptions\ViewException

### ISSUE THREAD

**Issue by gustiagungmurahadi** [ikhsan3adi/absensi-sekolah-qr-code#101]
![eror](https://github.com/user-attachments/assets/26430d32-bbe4-4293-8411-2beba0fc2106)

**Comment by ikhsan3adi** [comment]
Errornya muncul setelah melakukan apa?

Apakah filenya dipindah/diganti nama?

**Comment by ikhsan3adi** [comment]
Saya sudah nemu errornya, saya fix dulu

**Comment by ikhsan3adi** [comment]
solved by #104
