### ISSUE TITLE
Import/Export Data Siswa

### ISSUE THREAD

**Issue by rifkihakim88** [ikhsan3adi/absensi-sekolah-qr-code#109]
Salam kenal mas Ikhsan, boleh saran mas. 
1. apakah bisa ditambahkan Import data masal siswa maupun data guru dengan menggunakan Excel (jika murid lebih dari 500 siswa, akan terasa pegal jika tambah data secara manual)
2. Menu ubah Tahun pelajaran

**Comment by hex4coder** [comment]
Saya telah membuat skrip python untuk import data dari data source absen disekolah kami 
Berikut adalah kode yang saya buat menggunakan script python:
`# program untuk upload data guru
# secara banyak
import openpyxl
import hashlib
import mysql.connector 

listKelasXI = [
    "kelas",
    6,
    7,
    8,
    9,
    1,
    11,
    10,
    2
]

listKelasXII = [
    "kelas XII",
    12,
    13,
    14,
    15,
    18,
    19,
    17,
    16
]

listKelasX = [
    "kelas X",
    5,
    20,
    21,
    3,
    4,
    22,
    23,
    24
]

# generate unique code
def generate_unique_code(nis, nama):
    hashes = ""
    hash_object = hashlib.sha1((nis + str(777) ).encode('utf-8') )
    pbHash = hash_object.hexdigest()
    hash1 = pbHash
    hash1 = hash1[:24]


    # md5 
    hash_object = hashlib.md5((nis + nama).encode('utf-8'))
    hash2 = hash_object.hexdigest()

    # final sampling
    hash_object = hashlib.md5((hash2 + nama).encode('utf-8'))
    datatoencode = hash_object.hexdigest() + hash1
    hashes = datatoencode

    return hashes




# delete all data
def deleteAllData(mydb):
    mycursor = mydb.cursor()

    sql = "DELETE FROM tb_siswa WHERE id_siswa != 0"

    mycursor.execute(sql)

    mydb.commit()

    print(mycursor.rowcount, "record(s) deleted")



# parsing data 
def parsingDataSource(filename, listKelas, startpoint=1):
    print("[INFO] - Starting reader")

    # Define variable to load the dataframe
    dataframe = openpyxl.load_workbook(filename)

    # Define variable to read sheet
    dataframe1 = dataframe.active

    # temporary data
    listdata = []


    # Iterate the loop to read the cell values
    id_siswa = startpoint - 1
    kelasindex = 0
    for row in range(1, dataframe1.max_row):
        indexcol = 0
        nama = ""
        nomorhp = ""
        jk = ""
        nis = ""
        kodeunik = ""
        id_kelas = ""
        valid = False


        # iterasi pengambilan data
        for col in dataframe1.iter_cols(0, dataframe1.max_column):
            data = (col[row].value)
            

            if data is not None:
                if indexcol == 0 and type(data) == int:
                    # nomor
                    valid = True
                    if data == 1:
                        # kelas baru
                        kelasindex = kelasindex + 1


                if valid:
                    if indexcol == 1:
                        # nis
                        dataar = data.split(" ")
                        if(len(dataar)) > 1:
                            nis = dataar[2]
                        else:
                            nis = dataar[0]
                    elif indexcol == 2:
                        # nama
                        nama = data
                    elif indexcol == 3 or indexcol == 4:
                        if str(data).upper() == "L":
                            jk = "Laki-laki"
                        else:
                            jk = "Perempuan"



            indexcol = indexcol + 1



        if nama != "" and nis != "" and jk != "":
            id_siswa = id_siswa + 1
            nama = nama.upper().strip()
            id_kelas = listKelas[kelasindex]
            kodeunik = generate_unique_code(nis, nama)
            tupdata = (id_siswa, nis, nama, id_kelas, jk, nomorhp, kodeunik )
            listdata.append(tupdata)

           
    print("[INFO] - Membaca data sebanyak ", len(listdata), " record.")

    return listdata




# input data
def insertdata(mydb, listdata):
    mycursor = mydb.cursor()

    sql = "INSERT INTO tb_siswa (id_siswa, nis, nama_siswa, id_kelas, jenis_kelamin, no_hp, unique_code) VALUES (%s, %s, %s, %s, %s, %s, %s)"
    val = listdata

    mycursor.executemany(sql, val)

    mydb.commit()

    print(mycursor.rowcount, "telah diinput.") 




# pisah data berdasarkan kelas
def listDataByKelasID(listData, id_kelas):
    listdata = []
    
    for data in listData:
        if data[3] == id_kelas:
            listdata.append(data)

    return listdata


# insert data for kelas XII
def insertDataKelasXII(start=1):
    # read data
    listdata = parsingDataSource("XII.xlsx", listKelasXII, start)
    total = 0

    # parsing per list kelas
    for kelas_id in listKelasXII:
        listOfData = listDataByKelasID(listdata, kelas_id)
        
        # kirim data ke server
        if len(listOfData) > 0:
            insertdata(mydb, listOfData)
            total = total + len(listOfData)
        else:
            print("ID Kelas ", kelas_id, " tidak valid")

    print("Total data yang masuk ", total, " record.")
    return total 


# insert data for kelas XI
def insertDataKelasXI(start=1):    
    # read data
    listdata = parsingDataSource("XI.xlsx", listKelasXI, start)
    total = 0

    # parsing per list kelas
    for kelas_id in listKelasXI:
        listOfData = listDataByKelasID(listdata, kelas_id)
        
        # kirim data ke server
        if len(listOfData) > 0:
            insertdata(mydb, listOfData)
            total = total + len(listOfData)
        else:
            print("ID Kelas ", kelas_id, " tidak valid")

    print("Total data yang masuk ", total, " record.")
    return total


# insert data for kelas X\
def insertDataKelasX(start=1):    
    # read data
    listdata = parsingDataSource("X.xlsx", listKelasX, start)
    total = 0

    # parsing per list kelas
    for kelas_id in listKelasX:
        listOfData = listDataByKelasID(listdata, kelas_id)
        
        # kirim data ke server
        if len(listOfData) > 0:
            insertdata(mydb, listOfData)
            total = total + len(listOfData)
        else:
            print("ID Kelas ", kelas_id, " tidak valid")

    print("Total data yang masuk ", total, " record.")
    return total




# connecting to the database
mydb = mysql.connector.connect(
  host="smkncampalagian.sch.id",
  user="root",
  password="anu",
  database="db_absensi"
)

print(mydb)



# hapus dulu semua data
deleteAllData(mydb)


# insert data kelas XI
total = insertDataKelasXI()

# insert data kelas XII
totalXII = insertDataKelasXII(start=total + 1)

# data kelas X
totalX = insertDataKelasX(start=total + totalXII + 1)`

**Comment by rifkihakim88** [comment]
apakah ada tutorialnya di YT?

**Comment by rifkihakim88** [comment]
Mas Ikhsan, apakah bisa script phyton di atas di kombinasikan/di ekseskusi dengan script PHP. karena saya masih awam untuk Phytonnya

**Comment by ikhsan3adi** [comment]
Saya tidak tahu caranya eksekusi script python di php, saya juga bukan pengguna python 😄

**Comment by rifkihakim88** [comment]
Siap mas Ikhsan. mudah-mudahan segera terealisasi fitur import/export excel data Guru dan Siswa. terima kasih mas Ikhsan

**Comment by reactmore** [comment]
saya lagi buat Importnya tapi csv,
untuk tahun ajaran sudah ada menu pengaturan #125 

Screen: 
![Screenshot 2024-08-01 163544](https://github.com/user-attachments/assets/6077f5b8-d199-408e-92a5-bd9ea8133529)
![Screenshot 2024-08-01 163146](https://github.com/user-attachments/assets/75d95084-4c2a-47f9-990d-f8b956fd1596)
![Screenshot 2024-08-01 163155](https://github.com/user-attachments/assets/3ace9f12-fd37-428d-bfcc-e5ced1a28319)
![Screenshot 2024-08-01 163212](https://github.com/user-attachments/assets/d9664099-fc47-4693-bd0d-21c591ac665f)

**Comment by rifkihakim88** [comment]
![Screenshot 2024-08-02 094920](https://github.com/user-attachments/assets/071e623b-dbb1-4581-ad9c-950d5513466b)
jikalau seperti ini kenapa yaa mas? tidak muncul complete

**Comment by reactmore** [comment]
> ![Screenshot 2024-08-02 094920](https://github.com/user-attachments/assets/071e623b-dbb1-4581-ad9c-950d5513466b)
> jikalau seperti ini kenapa yaa mas? tidak muncul complete

Ada error mas, ada log nya gk ? Atau kirim csv nya

**Comment by rifkihakim88** [comment]
> > ![Screenshot 2024-08-02 094920](https://private-user-images.githubusercontent.com/176004679/354443265-071e623b-dbb1-4581-ad9c-950d5513466b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODA3NDIsIm5iZiI6MTcyMjU4MDQ0MiwicGF0aCI6Ii8xNzYwMDQ2NzkvMzU0NDQzMjY1LTA3MWU2MjNiLWRiYjEtNDU4MS1hZDljLTk1MGQ1NTEzNDY2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwNjM0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWFkMmRlOWM1MDgxNDBiOWE0ZjI5YjBlOWFiNjBiZmQzOTcxNGQ1ZTczYjcxNmQyNWIyNzBhYjk3ZGRhYTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e_STH97eVo4yScMI_N9HWXp5TwxMuHUSO41caL1EOGE)
> > jikalau seperti ini kenapa yaa mas? tidak muncul complete
> 
> Ada error mas, ada log nya gk ? Atau kirim csv nya

Sudah solved mas, CSV saya pakai (;) yang harusnya (,). setelah saya replace alhamdulillah sudah berhasil. terima kasih banyak

**Comment by rifkihakim88** [comment]
![image](https://github.com/user-attachments/assets/0df9d9f2-97d7-4d31-a582-bf7da653e125)
Jika waktu download QR Code bermasalah seperti kenapa ya mas?
waktu di generate juga ndak ada proses

**Comment by reactmore** [comment]
Fix Siswa QR Download: https://github.com/ikhsan3adi/absensi-sekolah-qr-code/pull/131/commits/141ef728f01b14b89b43aee2c0c38680b0b60528

**Comment by reactmore** [comment]
> ![image](https://private-user-images.githubusercontent.com/176004679/354501099-0df9d9f2-97d7-4d31-a582-bf7da653e125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODM1NTIsIm5iZiI6MTcyMjU4MzI1MiwicGF0aCI6Ii8xNzYwMDQ2NzkvMzU0NTAxMDk5LTBkZjlkOWYyLTk3ZDctNGQzMS1hNTgyLWJmN2RhNjUzZTEyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwNzIwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWQ3NjFiODkzMmNhMjRkOWZhZGM5ZmVhMDg1YTM3N2QxMmJiYzE3YWJiMmQ2ODUzOTA5ZGNiOTljY2UwZmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UjgMszqYNitDc86eDNcofh6ZRw4q_wHPtSET2dPQxfc) Jika waktu download QR Code bermasalah seperti kenapa ya mas? waktu di generate juga ndak ada proses

masalah path yaa

**Comment by reactmore** [comment]
![image](https://github.com/user-attachments/assets/e031cb07-be50-44ea-8184-45c663fe2c0e)
