### ISSUE TITLE
Agar tampilan camera lebih responsif di hp

### ISSUE THREAD

**Issue by kevindoni** [ikhsan3adi/absensi-sekolah-qr-code#11]
**Agar tampilan camera lebih responsif di hp**
_cari file di /app/Views/templates/starting_page_layout.php_

ganti line 36 dan 37 menjadi 

width: auto;
height: auto;

**untuk yang mau mengaktifkan pilihan kamera** 
_cari dan edit bagian /app/Views/templates/navbar.php_

line ke 47 - 51

![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/22675011/c8c29f43-e313-44fa-bf76-346964704904)

                      

**_hilangkan tanda comment nya_**

**Comment by ikhsan3adi** [comment]
Coba pull request bang
