### ISSUE TITLE
[BUG] Membuat tahun ajaran / angkatan pada header tabel menjadi dinamis.

### ISSUE THREAD

**Issue by hex4coder** [ikhsan3adi/absensi-sekolah-qr-code#110]
**Jelaskan bug tersebut**
Tahun ajaran yang statik harusnya bisa di edit seperti nama sekolah pada file config.

**Screenshots**
![image](https://github.com/user-attachments/assets/663a38fa-6e8e-4c22-bb0c-f91560e929c3)

**Solusi yang diminta**
Tambahkan source code untuk perubahan tahun ajaran / angkatan di file config.

**Comment by ikhsan3adi** [comment]
Oke saya cek
