### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ninkuneo07** [ikhsan3adi/absensi-sekolah-qr-code#116]
**Jelaskan bug tersebut**

 eror saat migrate seperti ini gimana pak

PS C:\xampp\htdocs\absensi-sekolah-qr-code-master> php spark migrate --all  
PHP Warning:  require(C:\xampp\htdocs\absensi-sekolah-qr-code-master\app\Config/../../vendor/codeigniter4/framework/system/Boot.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\absensi-sekolah-qr-code-master\spark on line 82

Warning: require(C:\xampp\htdocs\absensi-sekolah-qr-code-master\app\Config/../../vendor/codeigniter4/framework/system/Boot.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\absensi-sekolah-qr-code-master\spark on line 82
PHP Fatal error:  Uncaught Error: Failed opening required 'C:\xampp\htdocs\absensi-sekolah-qr-code-master\app\Config/../../vendor/codeigniter4/framework/system/Boot.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\absensi-sekolah-qr-code-master\spark:82
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\absensi-sekolah-qr-code-master\spark on line 82

Fatal error: Uncaught Error: Failed opening required 'C:\xampp\htdocs\absensi-sekolah-qr-code-master\app\Config/../../vendor/codeigniter4/framework/system/Boot.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\absensi-sekolah-qr-code-master\spark:82
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\absensi-sekolah-qr-code-master\spark on line 82
PS C:\xampp\htdocs\absensi-sekolah-qr-code-master>

**Comment by ikhsan3adi** [comment]
Sudah run `composer install`?

**Comment by Ninkuneo07** [comment]
sudah tapi muncul  git was not found in your PATH, skipping source download  pakk

**Comment by Ninkuneo07** [comment]
![Screenshot 2024-07-23 002406](https://github.com/user-attachments/assets/5a6853ba-8341-439f-ba05-a3cbf0f06cb4)

**Comment by Ninkuneo07** [comment]
maaf sudah bisak pak terimakasihhh
