### ISSUE TITLE
[BUG] Hasil Generate Laporan Tidak Sesuai Nama Barcode

### ISSUE THREAD

**Issue by RZKprojek** [ikhsan3adi/absensi-sekolah-qr-code#133]
**Jelaskan bug tersebut**
Hasil Generate Laporan Setelah Scan Barcode status yang berubah tidak sesuai dengan nama barcode yang discan
misalkan
Ada Barcode si Budi dan si Tari status awal keduanya Alpha
kemudian saya melakukan scan barcode menggunakan barcode budi
dengan harapan status budi dari alpha menjadi Hadir

namun tidak demikian saya scan barcode si budi yang berubah status malah si tari.

**Screenshots**
-

**Versi yang digunakan**
2023

**Versi PHP**
Contoh PHP XAMPP VERSION 8.1.25

semoga dijawab matur nuwun

**Comment by Eri31-lgtm** [comment]
Di cek programnya lgi
Sudah di update sama developernya

**Comment by RZKprojek** [comment]
> Di cek programnya lgi Sudah di update sama developernya

Boleh spill link source code terupdatenya?
