### ISSUE TITLE
500 error di console, tidak bisa generate qr code , di lokal bisa di hosting tidak bisa.

### ISSUE THREAD

**Issue by cakudin88** [ikhsan3adi/absensi-sekolah-qr-code#16]
500 error di console dan tidak tanpak response tidak bisa generate qr code , di lokal bisa di hosting tidak bisa.

**Comment by ikhsan3adi** [comment]
Kemungkinan karena konfigurasi di lokal dan di tempat hostingnya beda.

Coba cek versi php minimal versi 8.1+
Cek extension php
Cek permission untuk menulis file di server

**Comment by cakudin88** [comment]
sudah semua kak sudah saya coba 8.1 dan 8.2 tapi masi tetap. untuk extensi sudah saya aktifkan intl dan gd
permision sudah buat 777 kak. tapi belum bisa generate qr code kak.

**Comment by ikhsan3adi** [comment]
coba enviroment ganti ke development trus lihat consolenya saat generate

**Comment by ikhsan3adi** [comment]
https://github.com/ikhsan3adi/absensi-sekolah-qr-code/issues/15#issuecomment-1711033465

**Comment by cakudin88** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/114711113/82eed03c-c168-42c5-ba04-f3db22c24d4d)
muncul kayak gitu kak.

**Comment by ikhsan3adi** [comment]
Pesan errrornya terpotong. Salin errornya coba

**Comment by cakudin88** [comment]
`
    "title": "Exception",
    "type": "Exception",
    "code": 500,
    "message": "Content type could not be determined for logo URL \"https://.sch.id/public/assets/img/logo_sekolah.jpg\"",
    "file": "/home/smpb7497/public_html/.sch.id/vendor/endroid/qr-code/src/ImageData/LogoImageData.php",
    "line": 114,
    "trace": [
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/endroid/qr-code/src/ImageData/LogoImageData.php",
            "line": 30,
            "function": "detectMimeTypeFromUrl",
            "class": "Endroid\\QrCode\\ImageData\\LogoImageData",
            "type": "::"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/endroid/qr-code/src/Writer/AbstractGdWriter.php",
            "line": 125,
            "function": "createForLogo",
            "class": "Endroid\\QrCode\\ImageData\\LogoImageData",
            "type": "::"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/endroid/qr-code/src/Writer/AbstractGdWriter.php",
            "line": 113,
            "function": "addLogo",
            "class": "Endroid\\QrCode\\Writer\\AbstractGdWriter",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/endroid/qr-code/src/Writer/PngWriter.php",
            "line": 25,
            "function": "write",
            "class": "Endroid\\QrCode\\Writer\\AbstractGdWriter",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/app/Controllers/Admin/QRGenerator.php",
            "line": 115,
            "function": "write",
            "class": "Endroid\\QrCode\\Writer\\PngWriter",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/app/Controllers/Admin/QRGenerator.php",
            "line": 78,
            "function": "generate",
            "class": "App\\Controllers\\Admin\\QRGenerator",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/codeigniter4/framework/system/CodeIgniter.php",
            "line": 934,
            "function": "generateQrSiswa",
            "class": "App\\Controllers\\Admin\\QRGenerator",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/codeigniter4/framework/system/CodeIgniter.php",
            "line": 499,
            "function": "runController",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/codeigniter4/framework/system/CodeIgniter.php",
            "line": 368,
            "function": "handleRequest",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/index.php",
            "line": 67,
            "function": "run",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        }
    ]
}`

**Comment by cakudin88** [comment]
"title": "Exception",
    "type": "Exception",
    "code": 500,
    "message": "Content type could not be determined for logo URL \"https://.sch.id/public/assets/img/logo_sekolah.jpg\"",
    "file": "/home/smpb7497/public_html/.sch.id/vendor/endroid/qr-code/src/ImageData/LogoImageData.php",
    "line": 114,
    "trace": [
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/endroid/qr-code/src/ImageData/LogoImageData.php",
            "line": 30,
            "function": "detectMimeTypeFromUrl",
            "class": "Endroid\\QrCode\\ImageData\\LogoImageData",
            "type": "::"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/endroid/qr-code/src/Writer/AbstractGdWriter.php",
            "line": 125,
            "function": "createForLogo",
            "class": "Endroid\\QrCode\\ImageData\\LogoImageData",
            "type": "::"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/endroid/qr-code/src/Writer/AbstractGdWriter.php",
            "line": 113,
            "function": "addLogo",
            "class": "Endroid\\QrCode\\Writer\\AbstractGdWriter",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/endroid/qr-code/src/Writer/PngWriter.php",
            "line": 25,
            "function": "write",
            "class": "Endroid\\QrCode\\Writer\\AbstractGdWriter",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/app/Controllers/Admin/QRGenerator.php",
            "line": 115,
            "function": "write",
            "class": "Endroid\\QrCode\\Writer\\PngWriter",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/app/Controllers/Admin/QRGenerator.php",
            "line": 78,
            "function": "generate",
            "class": "App\\Controllers\\Admin\\QRGenerator",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/codeigniter4/framework/system/CodeIgniter.php",
            "line": 934,
            "function": "generateQrSiswa",
            "class": "App\\Controllers\\Admin\\QRGenerator",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/codeigniter4/framework/system/CodeIgniter.php",
            "line": 499,
            "function": "runController",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/vendor/codeigniter4/framework/system/CodeIgniter.php",
            "line": 368,
            "function": "handleRequest",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "/home/smpb7497/public_html/.sch.id/index.php",
            "line": 67,
            "function": "run",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        }
    ]
}

**Comment by ikhsan3adi** [comment]
Kalo error itu saya kurang tau sih.
Mungkin solusinya bisa dihilangkan saja logo di qr codenya

> ```php
>       // Create logo
>       $this->logo = Logo::create(base_url('public/assets/img/logo_sekolah.jpg'))->setResizeToWidth(75); // hapus ini
> 
>       // Save it to a file
>       $this->writer
>          ->write(qrCode: $this->qrCode, logo: $this->logo, label: $this->label)
>          ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
> ```
> 
> jadi:
> 
> ```php
>       // Save it to a file
>       $this->writer
>          ->write(qrCode: $this->qrCode, label: $this->label)
>          ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
> ```

**Comment by cakudin88** [comment]
betul mas memang saya cari2 g ada . memang solusinya menghilangkan logo sekolah mas dan akhirnya generate berjalan.

**Comment by scardbypass** [comment]
> Kalo error itu saya kurang tau sih. Mungkin solusinya bisa dihilangkan saja logo di qr codenya
> 
> > ```
> >       // Create logo
> >       $this->logo = Logo::create(base_url('public/assets/img/logo_sekolah.jpg'))->setResizeToWidth(75); // hapus ini
> > 
> >       // Save it to a file
> >       $this->writer
> >          ->write(qrCode: $this->qrCode, logo: $this->logo, label: $this->label)
> >          ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > jadi:
> > ```
> >       // Save it to a file
> >       $this->writer
> >          ->write(qrCode: $this->qrCode, label: $this->label)
> >          ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
> > ```

Ini posisi nya di folder apa ya kak

**Comment by AdhaTito** [comment]
saya udh coba hapus logo seperti di comment atas dan ganti tanda kutip di ' jadi ` ![code12](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/90611998/8da91d12-b6ac-4e2d-8615-8e183a614acc) ttp error nya masih sama seperti ini
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/90611998/0634d50e-0193-47a3-a328-8cea62a550e6)

**Comment by AdhaTito** [comment]
ekstension php mysql udh diaktifkan jg intl dan gd

**Comment by ikhsan3adi** [comment]
> ekstension php mysql jg udh diaktifkan jg intl dan gd

Supaya pesan error terlihat
https://github.com/ikhsan3adi/absensi-sekolah-qr-code/issues/15#issuecomment-1711033465

**Comment by AdhaTito** [comment]
[image: image.png] No response

Pada Sen, 15 Apr 2024 pukul 02.00 Ikhsan Satriadi ***@***.***>
menulis:

**Comment by AdhaTito** [comment]
> > ekstension php mysql jg udh diaktifkan jg intl dan gd
> 
> Supaya pesan error terlihat [#15 (comment)](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/issues/15#issuecomment-1711033465)

No response 
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/90611998/599072a7-50ba-47d3-b0b3-736f60652a57)

**Comment by ikhsan3adi** [comment]
Pake mode development

Di file `.env`

**Comment by AdhaTito** [comment]
> Pake mode development
> 
> Di file `.env`

sudah berhasil kak :), ternyata pake localhost:8080 gk bisa ya load websitenya jdi lama
