### ISSUE TITLE
"internal server error" ketika scan qr siswa

### ISSUE THREAD

**Issue by d0ubleyuu** [ikhsan3adi/absensi-sekolah-qr-code#18]
Mengapa pada scan qr presensi siswa mengemblikan eror "internal server error"

**Comment by ikhsan3adi** [comment]
Buka file `.env` lalu ubah CI_ENVIRONMENT dari production menjadi development.

Step selanjutnya buka console ,lalu ulangi aksi yang membuat error.
Klik tombol di ujung kanan.

![IMG-20230908-WA0011.jpg](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/93766033/493a158f-ced6-4626-a07b-e658aca3ac86)

Coba klik yang itu lalu lihat tab response

![Screenshot from 2023-09-08 10-31-24.png](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/93766033/c1867a3a-8515-4a87-bcf5-e89baed5b373)

**Comment by arssatya** [comment]
> Mengapa pada scan qr presensi siswa mengemblikan eror "internal server error"

udah solve?

**Comment by d0ubleyuu** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/116260085/b3a5b496-346a-4041-aa81-7af485ca11d2)

**Comment by ikhsan3adi** [comment]
> ![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/116260085/b3a5b496-346a-4041-aa81-7af485ca11d2)
> 

Ini udah pernah saya fix, coba download ulang yang versi terbaru

**Comment by irfandd** [comment]
> > ![image](https://user-images.githubusercontent.com/116260085/275574465-b3a5b496-346a-4041-aa81-7af485ca11d2.png)
> 
> Ini udah pernah saya fix, coba download ulang yang versi terbaru

saya baru unduh package nya kemarin (06-11-2023) errornya masih sama nih "internal server error" ketika scan qr code siswa, padahal sudah ubah CI_ENVIRONMENT dari production menjadi development pak.. 
datanya masuk di database dan aplikasi memang, persis seperti gambar diatas kode dan message errornya.

mohon arahannya pak
