### ISSUE TITLE
Masukan Absen RFID

### ISSUE THREAD

**Issue by githubnazi** [ikhsan3adi/absensi-sekolah-qr-code#2]
Apakah bisa dibuatkaan mode masukan lain selain QR CODE, misal menggunakan RFID?

**Comment by ikhsan3adi** [comment]
Terima kasih telah mengajukan pertanyaan! Mengenai permintaan Anda untuk menambahkan mode masukan selain QR Code, seperti menggunakan RFID, saat ini aplikasi absensi hanya mendukung metode masukan melalui QR Code.

QR Code dipilih sebagai metode masukan karena memiliki beberapa keuntungan, termasuk kemudahan penggunaan, biaya yang relatif rendah, dan dapat diakses dengan mudah melalui perangkat seluler yang umum digunakan.

Meskipun saat ini aplikasi hanya mendukung QR Code, kami akan mencatat permintaan Anda untuk menambahkan dukungan RFID sebagai mode masukan alternatif. Kami akan mempertimbangkan permintaan ini untuk pengembangan dan pembaruan masa depan.

**Comment by githubnazi** [comment]
Jika saya ubah sendiri untuk menambahkan mode RFID boleh ya? 
Dan juga untuk laporannya klo bisa ada yg excel juga agar datanya bisa digunkana untuk hal lainnya misal untuk penghitungan payroll dll.

**Comment by ikhsan3adi** [comment]
Kami sangat terbuka terhadap kontribusi dan partisipasi komunitas dalam pengembangan proyek ini. Jika Anda ingin membuat perubahan atau menambahkan mode masukan RFID sendiri, kami mendorong Anda untuk melakukannya.

Kami sarankan anda untuk membuat branch atau fork dari repository ini agar perubahan yang Anda buat dapat dinilai dan diperiksa secara terpisah sebelum diintegrasikan ke repositori utama.

Mengenai permintaan untuk menambahkan laporan dalam format Excel. Saat ini, aplikasi absensi belum memiliki fitur laporan dalam format Excel, karena kami sudah mencobanya namun hasilnya kurang memuaskan. Tetapi kami akan mencatat permintaan ini dan mempertimbangkannya untuk pengembangan dan pembaruan.
