### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by bimowahyu** [ikhsan3adi/absensi-sekolah-qr-code#24]
ketika scan absen masuk dan pulang tidak menampilkan data yang ada,tetapi berjalan di database dengan baik

![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/128451452/d0f46e62-bf9e-415f-93a1-b94f5b0db17c)

**Comment by bimowahyu** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/128451452/45563c4d-c241-4310-8da4-43b496187b4f)
pada file scan-result.php dan error-scan-result.php saya menghapus jurusan dan bisa menampilkan data siswa

**Comment by irfandd** [comment]
FIXED ngikutin tips @bimowahyu terkait internal server error.. thx!
