### ISSUE TITLE
"internal server error" generit 

### ISSUE THREAD

**Issue by scardbypass** [ikhsan3adi/absensi-sekolah-qr-code#25]
Cara atas in "internal server error" di hosting rumah web pada saat mau ambil data QR nya

**Comment by ikhsan3adi** [comment]
Coba lihat https://github.com/ikhsan3adi/absensi-sekolah-qr-code/issues/10#issuecomment-1667703479

Kemungkinan masalah di qr logonya

**Comment by scardbypass** [comment]
> Coba lihat [#10 (comment)](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/issues/10#issuecomment-1667703479)
> 
> Kemungkinan masalah di qr logonya

Ini benar di hilangkan gambar baru bisa
