### ISSUE TITLE
RouteCollection 

### ISSUE THREAD

**Issue by irfandd** [ikhsan3adi/absensi-sekolah-qr-code#26]
CodeIgniter v4.4.3 Command Line Tool - Server Time: 2023-11-06 20:18:38 UTC+07:00

[TypeError]

CodeIgniter\Router\RouteCollection::__construct(): Argument #3 ($routing) must be of type Config\Routing, null given, called in C:\xampp-8.1.12\htdocs\absensi\vendor\codeigniter4\framework\system\Config\Services.php on line 618

at SYSTEMPATH\Router\RouteCollection.php:285
-------
mohon infonya pak, settingan composernya blm ada yg dirubah2 padahal.

**Comment by irfandd** [comment]
FIXED

composer.lock di delete, composer.json nya dirubah ke 4.3.5 = "codeigniter4/framework": "4.3.5"
kemudian index.php nya line 34, dihapus satu titik (dot) menjadi = require FCPATH . './app/Config/Paths.php';

hasilnya work aplikasinya, ijin coba aplikasinya pak

**Comment by ikhsan3adi** [comment]
Sekarang pake ci terbaru (4.4.0+) juga sudah bisa. Sudah di fix di update terbaru.
