### ISSUE TITLE
saat di hosting error

### ISSUE THREAD

**Issue by attilaibza** [ikhsan3adi/absensi-sekolah-qr-code#3]
saat di hosting syntax error, unexpected identifier "Kehadiran"

**Comment by ikhsan3adi** [comment]
Coba berikan keterangan errornya lebih detail mas, mungkin bisa dikasih screenshotnya pas error.

**Comment by kevindoni** [comment]
Tidak bisa generate qrcode mas pas di hosting.,kalau di local host semua lancar

**Comment by kevindoni** [comment]
![eror](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/22675011/ac579dbc-e79d-43ff-b77e-9ab35bd93bf4)

**Comment by ikhsan3adi** [comment]
Sebelumnya terdapat error dikarenakan kesalahan dalam menentukan path untuk output qrcode-nya, dan sudah saya tangani.

Saya sudah memperbaiki dan membuat release terbaru.
Silakan cloning ulang project ini atau mendownload zipnya di `releases`

**Comment by kevindoni** [comment]
Masih sama mas,untuk generate qr nya gak ada respond....udah download yang terbaru juga...kalau di localhost sih aman aman aja...semua lancar bisa untuk generate,tapi pas di hosting di klik generate qr gak ada respond,eror seuai di pic atas

**Comment by kevindoni** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/22675011/a40516ba-5472-4ff9-9646-0bde7cb0f2b4)


ini respond header nya

**Comment by ikhsan3adi** [comment]
> ![Untitled](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/93766033/b145d570-a461-4d8c-825e-16b1dd8f7531)
> 
> Dari yang saya tangkap sih kayanya ada masalah di logonya. Mungkin formatnya tidak sesuai, coba ganti logo lain

Kasusnya mirip seperti di #10

**Comment by attilaibza** [comment]
Saat ini error nya ketika login dia kurang  table users dan auth_logins tpi kalau di local aman

**Comment by ikhsan3adi** [comment]
Coba migrasi ulang databasenya

**Comment by kevindoni** [comment]
> Coba `CI_ENVIRONMENT` ganti ke development di `.env` biar errornya kelihatan
> 
> Lalu lihat response nya


setelah neghilangkan $this->logo = Logo::create(base_url('public/assets/img/logo_sekolah.jpg'))->setResizeToWidth(75); responnya seperti itu


    "title": "Error",
    "type": "Error",
    "code": 500,
    "message": "Typed property App\\Controllers\\Admin\\QRGenerator::$logo must not be accessed before initialization",

**Comment by ikhsan3adi** [comment]
> ```php
>       // Create logo
>       $this->logo = Logo::create(base_url('public/assets/img/logo_sekolah.jpg'))->setResizeToWidth(75); // hapus ini
> 
>       // Save it to a file
>       $this->writer
>          ->write(qrCode: $this->qrCode, logo: $this->logo, label: $this->label)
>          ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
> ```
> 
> jadi:
> 
> ```php
>       // Save it to a file
>       $this->writer
>          ->write(qrCode: $this->qrCode, label: $this->label)
>          ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
> ```

Yang di bawah juga hapus di `$this->writer->write(...)`

**Comment by kevindoni** [comment]
Terimakasih bantuan dan sourcode nya mas....sekarang sudah berjalan normal untuk generate qr code nya

**Comment by attilaibza** [comment]
kalau qr tetap mau pakai logo itu harus sesuain dulu ya logo nya

**Comment by ikhsan3adi** [comment]
> kalau qr tetap mau pakai logo itu harus sesuain dulu ya logo nya
> 

Yang penting gambarnya kotak 1:1 supaya tidak menutupi qrnya terlalu banyak,
dan nama filenya bawaannya `logo_sekolah.jpg`.

Atau bisa diubah konfigurasinya di `app/Controllers/Admin/QRGenerator.php`

```php
      // Create logo 
       $this->logo = Logo::create(base_url('public/assets/img/logo_sekolah.jpg'))->setResizeToWidth(75);
```
