### ISSUE TITLE
php spark migrate error

### ISSUE THREAD

**Issue by diengoes** [ikhsan3adi/absensi-sekolah-qr-code#30]
ketika melakukan migrasi database menggunakan perintah; php spark migrate --all itu error
muncul seperti ini :
PHP Fatal error:  Uncaught Error: Undefined constant "CodeIgniter\ENVIRONMENT" in D:\xampp\htdocs\absensi\vendor\codeigniter4\framework\system\CodeIgniter.php:595
Stack trace:
#0 D:\xampp\htdocs\absensi\vendor\codeigniter4\framework\system\CodeIgniter.php(207): CodeIgniter\CodeIgniter->bootstrapEnvironment()
#1 D:\xampp\htdocs\absensi\spark(83): CodeIgniter\CodeIgniter->initialize()
#2 {main}
  thrown in D:\xampp\htdocs\absensi\vendor\codeigniter4\framework\system\CodeIgniter.php on line 595

Fatal error: Uncaught Error: Undefined constant "CodeIgniter\ENVIRONMENT" in D:\xampp\htdocs\absensi\vendor\codeigniter4\framework\system\CodeIgniter.php:595    
Stack trace:
#0 D:\xampp\htdocs\absensi\vendor\codeigniter4\framework\system\CodeIgniter.php(207): CodeIgniter\CodeIgniter->bootstrapEnvironment()
#1 D:\xampp\htdocs\absensi\spark(83): CodeIgniter\CodeIgniter->initialize()
#2 {main}
  thrown in D:\xampp\htdocs\absensi\vendor\codeigniter4\framework\system\CodeIgniter.php on line 595

mohon solusinya

**Comment by diengoes** [comment]
setelah dicoba lg tetap tidak bisa, tapi muncul seperti ini:
 php spark migrate --all

CodeIgniter v4.4.3 Command Line Tool - Server Time: 2023-11-22 08:23:06 UTC+07:00


[TypeError]

CodeIgniter\Router\RouteCollection::__construct(): Argument #3 ($routing) must be of type Config\Routing, null given, called in D:\xampp\htdocs\attendance\vendor\codeigniter4\framework\system\Config\Services.php on line 618

at SYSTEMPATH\Router\RouteCollection.php:285

mohon solusinya

**Comment by suta30** [comment]
sama bg, apa sdh nemu solusinya ?

**Comment by ikhsan3adi** [comment]
Sudah di fix di update terbaru. Bisa download ulang
