### ISSUE TITLE
bug composer

### ISSUE THREAD

**Issue by daveyedgartanibulie** [ikhsan3adi/absensi-sekolah-qr-code#34]
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - codeigniter4/framework[4.0.0, ..., v4.4.3] require ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.
    - Root composer.json requires codeigniter4/framework ^4.0 -> satisfiable by codeigniter4/framework[4.0.0, ..., v4.4.3].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-intl` to temporarily ignore these required extensions.
ini bagaimana ya

**Comment by ikhsan3adi** [comment]
Buka file `C:\xampp\php\php.ini` cari `;extension=intl` hapus titik koma menjadi `extension=intl`

**Comment by daveyedgartanibulie** [comment]
ook makasih kak
