### ISSUE TITLE
Generate QR Code

### ISSUE THREAD

**Issue by suta30** [ikhsan3adi/absensi-sekolah-qr-code#36]
Hi kk, kenapa Generate QR Code gak bisa ya, stuck pas klik generate all data siswa / guru. 
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/141900747/75aef0a5-573f-461b-b8b3-9c256127639f)

**Comment by ikhsan3adi** [comment]
Localhost atau hosting?

**Comment by ikhsan3adi** [comment]
Coba download ulang zipnya (bukan di `release`)
Kemarin ada perbaikan bug di qr generator

**Comment by suta30** [comment]
siap sdh bsa, tmks bg
