### ISSUE TITLE
Halaman Petugas

### ISSUE THREAD

**Issue by ilhan-syahrifal12** [ikhsan3adi/absensi-sekolah-qr-code#37]
![Screenshot 2023-12-08 001143](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/127981800/1b154d84-e6f5-4a0d-88ef-2b2bd45114fd)

Login sebagai Superadmin tapi button ke halaman petugasnya tidak muncul

**Comment by ilhan-syahrifal12** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/127981800/568b70f3-cbb3-430a-b73f-7905f7df302c)
Sudah men-klik tombol ini tapi halaman petugas tidak muncul juga.

![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/127981800/2d98c139-4695-4e0c-bec7-5c7739d882f5)
Mencoba akses halaman petugas melalui URL dan halaman berhasil terbuka, tetapi malah muncul pesan error seperti berikut
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/127981800/82c0b32a-053d-4ac4-a3ef-9d183ec0d09e)

**Comment by ikhsan3adi** [comment]
Coba ubah `.env` environment ke mode `development` supaya errornya terlihat
