### ISSUE TITLE
Error whoops we seem to have hit a snag. please try again later

### ISSUE THREAD

**Issue by aanndy7** [ikhsan3adi/absensi-sekolah-qr-code#4]
Permisi, izin bertanya, saya dapet kendala muncul error whoops we seem to have hit a snag. please try again later, mohon solusinya

**Comment by ikhsan3adi** [comment]
Kemungkinan error tersebut disebabkan extension yang belum diaktifkan. 

- Buka file php.ini yang berada pada folder : C:\xampp\php\php.ini, kemudian ikuti konfigurasi berikut :
```
;extension=intl
```
- Kemudian rubah menjadi (hapus tanda titik koma) :
```
extension=intl
```
Restart xampp

**Comment by notandz** [comment]
tetep ndak bisa mas

**Comment by aanndy7** [comment]
Iyaa, tetap mas 😂

Pada tanggal Sen, 7 Agu 2023 12.35, Ananda Putra ***@***.***>
menulis:

**Comment by ikhsan3adi** [comment]
Saya sudah melakukan update dan perbaikan serta memperbarui isi readme.md, silahkan download ulang lalu ulangi step-step yang ada di readme-nya.

**Comment by aanndy7** [comment]
Baik, terima kasih mas

Pada tanggal Sen, 7 Agu 2023 pukul 14.41 Ikhsan Satriadi <
***@***.***> menulis:

**Comment by notandz** [comment]
solved, masalah masnya kemungkinan error di db connection, gunakan migrate dengan benar
