### ISSUE TITLE
Scan QR masuk dan keluar

### ISSUE THREAD

**Issue by avrzll** [ikhsan3adi/absensi-sekolah-qr-code#43]
Pada saat scan kode QR muncul tulisan Internal Server Eror setelah kode QR terdeteksi dan data absensi tidak masuk di dashboard
![Screenshot 2023-12-24 165002](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/106380642/d9079f52-0daa-4d12-b626-172b7f8825d7)
![Screenshot 2023-12-24 164952](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/106380642/0846ef81-3405-4fe9-a12d-6396f5f85e0b)

**Comment by ikhsan3adi** [comment]
Pakai source code terbaru atau download versi tertentu?

**Comment by avrzll** [comment]
> Gunakan kode sumber terbaru atau unduh versi tertentu?

Langsung git clone dari github ini

**Comment by ikhsan3adi** [comment]
> > Gunakan kode sumber terbaru atau unduh versi tertentu?
> 
> Langsung git clone dari github ini

Sudah saya fix di commit terbaru. Coba clone ulang
