### ISSUE TITLE
Mohon maaf Kenapa Begini ya?

### ISSUE THREAD

**Issue by wirakarta** [ikhsan3adi/absensi-sekolah-qr-code#44]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/154517573/0969a3ba-9c35-4267-a462-450fced05d07)
 kenapa begini ya suhu? mohon bimbingannya

**Comment by ikhsan3adi** [comment]
Coba ubah file `.env`

```
ENVIRONMENT=production

// ubah ke
ENVIRONMENT=development
```

Nanti errornya bisa dilihat

**Comment by wirakarta** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/154517573/ef380a33-ca19-4f4c-8053-453c161f5d66)
begini :(

**Comment by wirakarta** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/154517573/22773169-75f8-44d8-8e17-ac51eca49efd)
errornya enum

**Comment by ikhsan3adi** [comment]
> ![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/154517573/ef380a33-ca19-4f4c-8053-453c161f5d66)
> begini :(

Error yang pertama seharusnya `\App\Views\admin\login` di `vendor/myth/auth/src/Config/Auth.php`

> ![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/154517573/22773169-75f8-44d8-8e17-ac51eca49efd)
> errornya enum

Yang kedua mungkin versi php yang dipakai masih dibawah 8.1 yang belum support enum

**Comment by wirakarta** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/154517573/28c632a1-1313-4a0b-9207-d5574266d471)
8.2 support ga suhu?

**Comment by wirakarta** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/154517573/2c24d5b9-4a1d-4be6-944a-9d2b752abd66)
terimakasih masalahnya di vendor/myth/auth/src/Config/Auth.php

**Comment by OyShan1** [comment]
> ![image](https://private-user-images.githubusercontent.com/154517573/292754312-2c24d5b9-4a1d-4be6-944a-9d2b752abd66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTc5OTUsIm5iZiI6MTcxMDIxNzY5NSwicGF0aCI6Ii8xNTQ1MTc1NzMvMjkyNzU0MzEyLTJjMjRkNWI5LTRhMWQtNGJlNi05NDRhLTlkMmI3NTJhYmQ2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwNDI4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGE2MmViMGJjMDYxZjkxMjNiMmRhZGVkMjExMTFlZjU4ZDBmMzQ3YzAxMTVjY2QwY2RiNmYzZDYxNjE4YWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HjnoU_VX31q4fWgToqqB-8BDuB85h9YQY9qu2-WycPk) terimakasih masalahnya di vendor/myth/auth/src/Config/Auth.php

Masalahnya di bagian mana nya bang?
