### ISSUE TITLE
Tampilan jadi berubah

### ISSUE THREAD

**Issue by wirakarta** [ikhsan3adi/absensi-sekolah-qr-code#47]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/154517573/80fa0014-eca4-4174-8d72-a1ea34d194a3)
kenapa ada icon CodeIgniter dan tampilan jadi kelihatan element dan kotak gitu ya bang :(

**Comment by ikhsan3adi** [comment]
Icon codeigniternya kepencet itu.
Kalo mau ilangin iconnya ubah file `.env`

```bash
CI_ENVIRONMENT=production 
# sebelumnya development
```
