### ISSUE TITLE
permasalahan saat buka menu laporan

### ISSUE THREAD

**Issue by lialubna** [ikhsan3adi/absensi-sekolah-qr-code#5]
selalu muncul wooops We seem to have hit a snag. Please try again later. saat membuka menu laporan

saya cek folder laporan memang tidak ada

mohon bantuannya

**Comment by ikhsan3adi** [comment]
Pastikan sudah mengikuti semua instruksi dengan benar, termasuk php extension.

Kalau tidak berhasil cobalah men-download ulang repositorynya.
