### ISSUE TITLE
Terdapat bug saat akan edit data siswa

### ISSUE THREAD

**Issue by avrzll** [ikhsan3adi/absensi-sekolah-qr-code#50]
Ketika mengedit data siswa laki laki, saat masuk di form edit, jenis kelaminnya jadi perempuan, jika yang menggunakan lalai tanpa memperhatikakn data, data siswa tersebut keubah jadi perempuan.

![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/106380642/b47c0460-e24a-42b7-b0fc-363409c606cd)
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/106380642/29ae73a6-406f-4a05-a13c-34153cc9f548)

Versi terbaru (sekitar 2 minggu lalu)

Versi PHP : 8.2.12

**Comment by ikhsan3adi** [comment]
Solved


```php
<?php
  // kode lama
  $l = (old('jk') ?? $oldInput['jk'] ?? $data['jenis_kelamin']) == 'Laki-laki' || '1' ? 'checked' : '';
  $p = (old('jk') ?? $oldInput['jk'] ?? $data['jenis_kelamin']) == 'Perempuan' || '2' ? 'checked' : '';
?>

<?php
  $jenisKelamin = (old('jk') ?? $oldInput['jk'] ?? $data['jenis_kelamin']);
  $l = $jenisKelamin == 'Laki-laki' || $jenisKelamin == '1' ? 'checked' : '';
  $p = $jenisKelamin == 'Perempuan' || $jenisKelamin == '2' ? 'checked' : '';
?>
```

Commit: https://github.com/ikhsan3adi/absensi-sekolah-qr-code/commit/d4a779eb31054ae32be572d0d41cf3daeec01acf
