### ISSUE TITLE
Generate QR Code Failed to load resource: the server responded with a status of 500 () generate [BUG]

### ISSUE THREAD

**Issue by alfaris123** [ikhsan3adi/absensi-sekolah-qr-code#55]
**Jelaskan bug tersebut**
saat generate QR code tidak ada barcode di folder public saat di ispek elemen muncul Failed to load resource: the server responded with a status of 500 () generate, otomatis kode qr gak ada

**Screenshots**
Jika ada

**Versi yang digunakan**
versi clone tanggal 05/02/2024

**Versi PHP**
PHP 8.2

**Comment by ikhsan3adi** [comment]
Apakah extension `gd` sudah diaktifkan?
Apakah sudah di hosting?

Mungkin ini bisa jadi referensi
https://github.com/ikhsan3adi/absensi-sekolah-qr-code/issues/16

**Comment by hex4coder** [comment]
Apakah folder storage sudah diset permissionnya dengan benar ?
