### ISSUE TITLE
[ERROR] error ketika melakukan migrasi data

### ISSUE THREAD

**Issue by vianziro** [ikhsan3adi/absensi-sekolah-qr-code#58]
**Jelaskan bug tersebut**

**Screenshots**
<img width="1245" alt="Screenshot 2024-04-22 at 01 04 36" src="https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/9649104/301e1fcc-cf7c-4cf5-8f00-7dfd25c7282b">

**Versi yang digunakan**
Tuliskan versi yang didownload (contoh: v1.5.3). Jika download via zip/clone berikan informasi waktu saat download source code.

**Versi PHP**
Contoh PHP 8.2

**Comment by ikhsan3adi** [comment]
Sudah saya fix di commit terbaru

**Comment by vianziro** [comment]
sudah saya coba tapi ketika imigrate dia masih error, padahal nama database sudah benar 
<img width="828" alt="Screenshot 2024-04-23 at 11 18 57" src="https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/9649104/b692f141-0932-4f9d-a312-1381fccb1ccd">

**Comment by vianziro** [comment]
saya install menggunakan mamp apakah ada aturan terkait penggunaan service ?

**Comment by ikhsan3adi** [comment]
Kalau itu saya kurang tahu karena bukan pengguna MacOS🙏

**Comment by vianziro** [comment]
<img width="1061" alt="Screenshot 2024-05-15 at 14 03 18" src="https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/9649104/b99b9f76-d636-40ce-85a9-1c6c114b3c93">


saya sudah cek semua setting, dan sudah benar tapi tetap tidak bisa

**Comment by ikhsan3adi** [comment]
Cek databasenya apakah sudah berjalan.
Cek juga port dan password database
