### ISSUE TITLE
mengatur jam masuk

### ISSUE THREAD

**Issue by lialubna** [ikhsan3adi/absensi-sekolah-qr-code#6]
bagaimana cara mengatur jam masuk ?
sehingga keterangan otomatis jika ada siswa terlambat

**Comment by ikhsan3adi** [comment]
Untuk mengatuk jam masuk, masuk ke menu absensi siswa/guru lalu pilih menu edit.

Saat ini aplikasi belum memiliki fitur keterangan otomatis jika absen terlambat, kami akan mencatat permintaan Anda untuk menambahkan fitur tersebut. Kami akan mempertimbangkan permintaan ini untuk pengembangan dan pembaruan masa depan.

**Comment by kevindoni** [comment]
Mungkin jika absen siswa di buat per jam pelajaran sepertinya lebih efektif untuk menghindari siswa bolos di jam pelajaran tertentu 😅

**Comment by kevindoni** [comment]
private function view_berkali(){
		$view=$this->M_absen->view_berkali_kali()->berapa_kali;
		if ($view=="bisa") {
			return "bisa";
		}elseif($view=="tidak") {
			return "tidak";
		}else{
			return "gagal";
		}
	}


mungkin bisa menambahkan seperti ini untuk absensi per jam pelajaran

**Comment by kevindoni** [comment]
sebagai refrensi 

![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/22675011/17e7a917-0197-44e7-9f0c-223d02f62bf2)


![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/22675011/5d93614b-5ad5-4704-acef-5a8deb2392e9)

**Comment by kevindoni** [comment]
**Absensi Controllers**

class Absensi extends CI_Controller {

       public function __construct() {
           parent::__construct();
           $this->load->model('Absensi_model');
       }

       public function index() {
           // Tampilkan halaman absensi siswa
           $this->load->view('absensi');
       }

       public function absen_siswa() {
           // Ambil data dari form
           $id_siswa = $this->input->post('id_siswa');
           $jam_pelajaran = $this->input->post('jam_pelajaran');

           // Cek apakah qrcode valid dan belum absen
           $is_valid = $this->Absensi_model->is_valid_qrcode($id_siswa, $jam_pelajaran);
           if ($is_valid) {
               // Tambahkan data absensi ke database
               $this->Absensi_model->tambah_absensi($id_siswa, $jam_pelajaran);

               // Tampilkan pesan berhasil absen
               echo json_encode(['status' => 'success', 'message' => 'Absensi berhasil']);
           } else {
               // Tampilkan pesan qrcode tidak valid atau sudah absen
               echo json_encode(['status' => 'error', 'message' => 'QRCode tidak valid atau anda sudah absen']);
           }
       }

   }



**Absensi_model**

class Absensi_model extends CI_Model {

       public function is_valid_qrcode($id_siswa, $jam_pelajaran) {
           // Cek apakah qrcode valid
           // Misalnya dengan membandingkan qrcode yang di-scan dengan data siswa dan jam pelajaran dari database

           // Jika qrcode valid, cek apakah sudah absen pada jam pelajaran yang sama hari ini
           $tanggal_absen = date('Y-m-d');
           $this->db->where('id_siswa', $id_siswa);
           $this->db->where('jam_pelajaran', $jam_pelajaran);
           $this->db->where('tanggal_absen', $tanggal_absen);
           $absen = $this->db->get('absensi_siswa')->row();

           return (!$absen) ? true : false;
       }

       public function tambah_absensi($id_siswa, $jam_pelajaran) {
           // Tambahkan data absensi ke database
           $tanggal_absen = date('Y-m-d');
           $data = array(
               'id_siswa' => $id_siswa,
               'jam_pelajaran' => $jam_pelajaran,
               'tanggal_absen' => $tanggal_absen
           );

           $this->db->insert('absensi_siswa', $data);
       }

   }


**absensi Views**

<!DOCTYPE html>
   <html>
   <head>
       <title>Absen Siswa</title>
   </head>
   <body>
       <h1>Absen Siswa</h1>

       <form id="form-absensi">
           <label for="id-siswa">ID Siswa:</label>
           <input type="text" name="id_siswa" id="id-siswa">

           <label for="jam-pelajaran">Jam Pelajaran:</label>
           <input type="text" name="jam_pelajaran" id="jam-pelajaran">

           <button type="submit">Absen</button>
       </form>

       <div id="absensi-result"></div>

       <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
       <script>
           $(function() {
               $('#form-absensi').submit(function(e) {
                   e.preventDefault();

                   var idSiswa = $('#id-siswa').val();
                   var jamPelajaran = $('#jam-pelajaran').val();

                   $.ajax({
                       url: '<?php echo site_url("absensi/absen_siswa"); ?>',
                       type: 'post',
                       dataType: 'json',
                       data: {id_siswa: idSiswa, jam_pelajaran: jamPelajaran},
                       success: function(response) {
                           $('#absensi-result').html(response.message);
                       }
                   });
               });
           });
       </script>
   </body>
   </html>
