### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by if7D0** [ikhsan3adi/absensi-sekolah-qr-code#62]
**Jelaskan bug tersebut**
Failed to generate qr code. Extensi -intl dan -gd sudah diaktifkan. Mode environment sudah development. Apakah ada solusi?

**Screenshots**
![Screenshot (469)](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/91078039/e25c4878-2c9e-48a0-9d86-2e5bb1538495)

**Versi yang digunakan**
v1.5.6

**Versi PHP**
PHP 8.2

**Comment by ikhsan3adi** [comment]
Coba hilangkan logonya di `app\Controllers\Admin\QRGenerator.php`

```php
      // Line 49
      $this->logo = Logo::create(base_url('public/assets/img/logo_sekolah.jpg'))->setResizeToWidth(75); // hapus ini

      // Line 116
      $this->writer
         ->write(qrCode: $this->qrCode, logo: $this->logo, label: $this->label)
         ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
```

jadi:

```php
      // Save it to a file
      $this->writer
         ->write(qrCode: $this->qrCode, label: $this->label)
         ->saveToFile(path: $this->relativePath . $this->qrCodeFilePath . $filename);
```

**Comment by ikhsan3adi** [comment]
Untuk sementara, update `vendor/myth/auth/src/Authentication/Passwords/ValidatorInterface.php` file:

```php
#use CodeIgniter\Entity;
use CodeIgniter\Entity\Entity;
```

sumber:
https://github.com/lonnieezell/myth-auth/issues/621#issue-2241692427
