### ISSUE TITLE
[Ask]

### ISSUE THREAD

**Issue by adiferianto** [ikhsan3adi/absensi-sekolah-qr-code#64]
Cara allow scan masuk lebih dari 1 kali, code yang mana ya ? yg perlu di updated

**Comment by adiferianto** [comment]
Big thanks

**Comment by adiferianto** [comment]
Oh iya menggunakan droidcam saat scan qrcode kok ga ada respons ya ? disisi windows (droidcam client) dan android (droid cam app) sudah terkoneksi dan sudah tampil camera nya

**Comment by adiferianto** [comment]
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/74529058/3ecc24ec-c5dd-4651-91b4-af1d3a307359)

Tampilan pada gambar terlampir yg menunjukan kalimat "absensi siswa dan guru berbasis qr code" code nya ada di direktori apa ya ?

**Comment by ikhsan3adi** [comment]
`app/Controllers/Scan.php` method `index`

**Comment by adiferianto** [comment]
![Screenshot_1](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/74529058/dbce736b-569c-4edd-a4fe-c6523e5f158c)

jika di ganti menggunakan URL Dinamis kenapa camera ga muncul ya ? atau ada code yg perlu di updated selain Config dan Constansts.php

**Comment by ikhsan3adi** [comment]
Sudah di izinkan belum di browsernya
