### ISSUE TITLE
Kenapa jadi seperti ini ya[BUG]

### ISSUE THREAD

**Issue by Wandiwijaya** [ikhsan3adi/absensi-sekolah-qr-code#65]
![20240504_092637_mfnr](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/165023149/347a3e98-9c33-43b7-a22b-786885d4c19b)

**Comment by ikhsan3adi** [comment]
Buat dulu databasenya lalu jalankan migrasi

Ada di readme

**Comment by Wandiwijaya** [comment]
> Buat dulu databasenya lalu jalankan migrasi
> 
> Ada di readme

Udah tapi sama gak bisa

**Comment by Wandiwijaya** [comment]
Kalo udh composer instal yg muncup cuma vendor nya aja kalo sql nya di mana ya?

**Comment by ikhsan3adi** [comment]
Tidak menggunakan file sql tapi menggunakan file migrasi yang ada di `app\Database\Migrations\`

> Buat database db_absensi di phpMyAdmin / mysql
> Penting ⚠️. Jalankan migrasi database untuk membuat struktur tabel yang diperlukan. Ketikkan perintah berikut di terminal:
> 
> ```bash
> php spark migrate --all
> ```

**Comment by ikhsan3adi** [comment]
`app/Controllers/Admin/GenerateLaporan.php`

```php
// line 90
      foreach ($period as $value) {
         // kecualikan hari sabtu dan minggu
         if (!($value->format('D') == 'Sat' || $value->format('D') == 'Sun')) {
            $lewat = Time::parse($value->format('Y-m-d'))->isAfter(Time::today());

            $absenByTanggal = $this->presensiSiswaModel
               ->getPresensiByKelasTanggal($idKelas, $value->format('Y-m-d'));

            $absenByTanggal['lewat'] = $lewat;

            array_push($dataAbsen, $absenByTanggal);
            array_push($arrayTanggal, $value);
         }
      }
```

**Comment by Wandiwijaya** [comment]
Yang mana kak?

**Comment by ikhsan3adi** [comment]
Hapus ininya aja

```php
if (!($value->format('D') == 'Sat' || $value->format('D') == 'Sun')) {

}
```

**Comment by Wandiwijaya** [comment]
![IMG-20240513-WA0078](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/165023149/2f6be1ce-f030-4bbf-bcfd-3bd876991b2c)
Mohon maaf kak
Kan aku udah generat laporan ya ...kok tidak sama kaya yang di absen siswa yg hadir sama yg sakit nya ....kali du absen siswa yang hadir 6 kalo di laporan cuman 5....itu gimana ya kak.....bisa di jelasin agar bisa sama di absen sama di laporan...🙏
Terimaksih
