### ISSUE TITLE
Tidak dapat generate QR[BUG]

### ISSUE THREAD

**Issue by Vikoo0** [ikhsan3adi/absensi-sekolah-qr-code#73]
**Jelaskan bug tersebut**
Setelah selesai buat data dan generate all tapi gambar tidak tampil di file public/uploads/qr-siswa/'kelas'/*kosong
bagaimana solusi nya?

**Screenshots**
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/149301558/4ea7dd8c-1c4f-4d9a-9988-ef195d265291)

**Comment by ikhsan3adi** [comment]
Sebelumnya sudah melakukan perubahan pada kode?

**Comment by Vikoo0** [comment]
hanya mengikuti step install di README.md dan belum mengubah lain2nya tapi tidak bisa generate QR
![image](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/149301558/829ea373-70f1-4e84-a42b-c0ab4d982baa)

**Comment by ikhsan3adi** [comment]
Coba ikuti #75

**Comment by Eri31-lgtm** [comment]
saya masih sama seperti itu error nya mas
mohon pencerahannya

**Comment by ikhsan3adi** [comment]
> saya masih sama seperti itu error nya mas
> mohon pencerahannya

Coba lihat #75

**Comment by Eri31-lgtm** [comment]
Saya mau caru errornya ada di file mana kurang tahu

Pada Sab, 29 Jun 2024, 00.04, Ikhsan Satriadi ***@***.***>
menulis:

**Comment by Eri31-lgtm** [comment]
Saya kurang pas ketika lihat #75

**Comment by Eri31-lgtm** [comment]
Ada muncul di bagian response, cuma saya bngung harus edit kode nya dimana
