### ISSUE TITLE
Cara mengetahui penyebab stuck saat generate QR Code atau muncul `Internal server error` di halaman scan

### ISSUE THREAD

**Issue by ikhsan3adi** [ikhsan3adi/absensi-sekolah-qr-code#75]
# Cara mengetahui penyebab terjadinya `500 Internal server error`

> Biasanya terjadi saat men-generate qr code progress bar tidak berjalan/stuck.
> Muncul pesan Internal server error setelah scan qr code di halaman scan.

- Ubah `CI_ENVIRONMENT` ke `development` di file `.env`:

```env
CI_ENVIRONMENT = development
# CI_ENVIRONMENT = production
```

- Di browser, pergi ke devtools atau tekan f12 lalu masuk ke tab console
- Refresh halaman yang terdapat error (halaman generate qr / halaman scan)
- Lalu lakukan aksi yang membuat error terjadi.

![IMG-20230908-WA0011.jpg](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/93766033/493a158f-ced6-4626-a07b-e658aca3ac86)

- Jika muncul error di console, klik tanda itu lalu lihat tab response (lihat gambar).

![Screenshot from 2023-09-08 10-31-24.png](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/93766033/c1867a3a-8515-4a87-bcf5-e89baed5b373)

- Jika tidak tahu cara memperbaiki sendiri error yang muncul, salin response yang muncul lalu buat issue baru dengan menyertai informasi tersebut.

> _Saat melaporkan error atau bug, alangkah baiknya untuk memberikan informasi terkait detail error yang terjadi agar perbaikan bug dapat dengan mudah dilakukan._

**Comment by lailaa60** [comment]
gabisa login petugas keterangan password eror
