### ISSUE TITLE
Generate Laporan

### ISSUE THREAD

**Issue by narham** [ikhsan3adi/absensi-sekolah-qr-code#78]
pada saat generate ke laporan prekelas PDF. terjadi miss antara Laporan bulanan dan Laporan Pertanggal.  

**Versi yang digunakan** 1.5.5

**Versi PHP**
Contoh PHP 8.2

**Comment by narham** [comment]
Tapi sdah d Perbaiki Bangg... semntara aman terkendali

**Comment by Eri31-lgtm** [comment]
maaf mas mau tanya, ini laporan kehadiran belum ada total dari sakit, izin, alfa klo misalnya mau di tambah total agr proses rekap kehadiran lebih cepat, bisa kan ya mas ?

**Comment by ikhsan3adi** [comment]
> maaf mas mau tanya, ini laporan kehadiran belum ada total dari sakit, izin, alfa klo misalnya mau di tambah total agr proses rekap kehadiran lebih cepat, bisa kan ya mas ?

Fitur ditambahkan di #100
