### ISSUE TITLE
Tidak bisa generate qr code

### ISSUE THREAD

**Issue by Eri31-lgtm** [ikhsan3adi/absensi-sekolah-qr-code#80]
Saya sudah menemukan error nya dimana melalui response dan mengikuti cara #75, namun langkah selanjutnya saya tidak mengerti. Mohon bimbingannya mas

**Comment by ikhsan3adi** [comment]
Salin atau screenshot aja errornya

**Comment by Eri31-lgtm** [comment]
![1](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/174134265/3597f2ea-236f-4e8b-9916-beb2e8161324)
![2](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/174134265/ee89c3e9-bb2c-4ba5-acdb-de445a8e035a)

**Comment by ikhsan3adi** [comment]
Coba salin mas itu ketutupan

**Comment by Eri31-lgtm** [comment]
{
    "title": "Exception",
    "type": "Exception",
    "code": 500,
    "message": "Unable to generate image: please check if the GD extension is enabled and configured correctly",
    "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\endroid\\qr-code\\src\\Writer\\AbstractGdWriter.php",
    "line": 26,
    "trace": [
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\endroid\\qr-code\\src\\Writer\\PngWriter.php",
            "line": 25,
            "function": "write",
            "class": "Endroid\\QrCode\\Writer\\AbstractGdWriter",
            "type": "->",
            "args": [
                {},
                null,
                {},
                {
                    "compression_level": -1
                }
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Controllers\\Admin\\QRGenerator.php",
            "line": 118,
            "function": "write",
            "class": "Endroid\\QrCode\\Writer\\PngWriter",
            "type": "->",
            "args": [
                {},
                null,
                {}
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Controllers\\Admin\\QRGenerator.php",
            "line": 78,
            "function": "generate",
            "class": "App\\Controllers\\Admin\\QRGenerator",
            "type": "->",
            "args": [
                "asep",
                "12346797",
                "bcb11e9845d604846db5856c958c06fae49e299e853cf8022b384fcdcde2489c"
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 933,
            "function": "generateQrSiswa",
            "class": "App\\Controllers\\Admin\\QRGenerator",
            "type": "->",
            "args": []
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 509,
            "function": "runController",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->",
            "args": [
                {}
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 355,
            "function": "handleRequest",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->",
            "args": [
                null,
                {
                    "handler": "file",
                    "backupHandler": "dummy",
                    "storePath": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\writable\\cache/",
                    "cacheQueryString": false,
                    "prefix": "",
                    "ttl": 60,
                    "reservedCharacters": "{}()/\\@:",
                    "file": {
                        "storePath": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\writable\\cache/",
                        "mode": 416
                    },
                    "memcached": {
                        "host": "127.0.0.1",
                        "port": 11211,
                        "weight": 1,
                        "raw": false
                    },
                    "redis": {
                        "host": "127.0.0.1",
                        "password": null,
                        "port": 6379,
                        "timeout": 0,
                        "database": 0
                    },
                    "validHandlers": {
                        "dummy": "CodeIgniter\\Cache\\Handlers\\DummyHandler",
                        "file": "CodeIgniter\\Cache\\Handlers\\FileHandler",
                        "memcached": "CodeIgniter\\Cache\\Handlers\\MemcachedHandler",
                        "predis": "CodeIgniter\\Cache\\Handlers\\PredisHandler",
                        "redis": "CodeIgniter\\Cache\\Handlers\\RedisHandler",
                        "wincache": "CodeIgniter\\Cache\\Handlers\\WincacheHandler"
                    }
                },
                false
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\codeigniter4\\framework\\system\\Boot.php",
            "line": 312,
            "function": "run",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->",
            "args": []
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\codeigniter4\\framework\\system\\Boot.php",
            "line": 67,
            "function": "runCodeIgniter",
            "class": "CodeIgniter\\Boot",
            "type": "::",
            "args": [
                {}
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\index.php",
            "line": 56,
            "function": "bootWeb",
            "class": "CodeIgniter\\Boot",
            "type": "::",
            "args": [
                {
                    "systemDirectory": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Config/../../vendor/codeigniter4/framework/system",
                    "appDirectory": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Config/..",
                    "writableDirectory": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Config/../../writable",
                    "testsDirectory": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Config/../../tests",
                    "viewDirectory": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Config/../Views"
                }
            ]
        }
    ]
}


ini mas

**Comment by ikhsan3adi** [comment]
Sepertinya extensi php `gd` belum terinstal

Ini cara pasangnya
https://youtu.be/JtN7UwLkWFA

**Comment by Eri31-lgtm** [comment]
baik mas saya coba dlu

**Comment by Eri31-lgtm** [comment]
> Sepertinya extensi php `gd` belum terinstal
> 
> Ini cara pasangnya https://youtu.be/JtN7UwLkWFA

mas klo file php.ini nya tdak ada bgaimana ?

**Comment by ikhsan3adi** [comment]
Biasanya di `C:\xampp\php\php.ini`

**Comment by Eri31-lgtm** [comment]
> Biasanya di `C:\xampp\php\php.ini`

adanya ini hanya
php.ini-development
php.ini-production

**Comment by ikhsan3adi** [comment]
Yang developmentnya copy jadi php.ini coba

**Comment by Eri31-lgtm** [comment]
mash blm bisa mas

**Comment by Eri31-lgtm** [comment]
sudah bisa mas alhmdllh terimakasih mas
