### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by gustiagungmurahadi** [ikhsan3adi/absensi-sekolah-qr-code#87]
404 not found padahal sudah mengkuti tutorial dengan benar
sudah di ulang beberapa kali namun sama saja
tidak ada keterangan eror di bagian mana
mohon pencerahan nya

![Screenshot 2024-07-09 215236](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/122070997/654f9a9c-9262-4f95-906f-450b84cb5322)

**Comment by ikhsan3adi** [comment]
Pastika folder sourcecode `absensi-sekolah-qr-code` sudah berada di folder htdocs

**Comment by gustiagungmurahadi** [comment]
okey okeyy bng
alhamdulillah sudah bisa
terimakasih banyak
berkah selalu
