### ISSUE TITLE
generate qr code

### ISSUE THREAD

**Issue by gustiagungmurahadi** [ikhsan3adi/absensi-sekolah-qr-code#89]
mau nanya min
pas mau generate qr code stuck gak muncul qr code nya itu kenapa yaa
yang jadi hanya file kosong 

![Screenshot 2024-07-10 212016](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/assets/122070997/80e35f28-64fb-41bc-bf42-66125be2fc8a)

**Comment by ikhsan3adi** [comment]
Coba lihat dulu #75

**Comment by gustiagungmurahadi** [comment]
{
    "title": "Exception",
    "type": "Exception",
    "code": 500,
    "message": "Unable to generate image: please check if the GD extension is enabled and configured correctly",
    "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\endroid\\qr-code\\src\\Writer\\AbstractGdWriter.php",
    "line": 26,
    "trace": [
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\endroid\\qr-code\\src\\Writer\\PngWriter.php",
            "line": 25,
            "function": "write",
            "class": "Endroid\\QrCode\\Writer\\AbstractGdWriter",
            "type": "->",
            "args": [
                {},
                {},
                {},
                {
                    "compression_level": -1
                }
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Controllers\\Admin\\QRGenerator.php",
            "line": 115,
            "function": "write",
            "class": "Endroid\\QrCode\\Writer\\PngWriter",
            "type": "->",
            "args": [
                {},
                {},
                {}
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Controllers\\Admin\\QRGenerator.php",
            "line": 75,
            "function": "generate",
            "class": "App\\Controllers\\Admin\\QRGenerator",
            "type": "->",
            "args": [
                "yaaya",
                "23456789",
                "7b714b07ada996702bddcfead4fc489eecb28d23ce477234634667be9f367d52"
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 933,
            "function": "generateQrSiswa",
            "class": "App\\Controllers\\Admin\\QRGenerator",
            "type": "->",
            "args": []
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 509,
            "function": "runController",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->",
            "args": [
                {}
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 355,
            "function": "handleRequest",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->",
            "args": [
                null,
                {
                    "handler": "file",
                    "backupHandler": "dummy",
                    "storePath": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\writable\\cache/",
                    "cacheQueryString": false,
                    "prefix": "",
                    "ttl": 60,
                    "reservedCharacters": "{}()/\\@:",
                    "file": {
                        "storePath": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\writable\\cache/",
                        "mode": 416
                    },
                    "memcached": {
                        "host": "127.0.0.1",
                        "port": 11211,
                        "weight": 1,
                        "raw": false
                    },
                    "redis": {
                        "host": "127.0.0.1",
                        "password": null,
                        "port": 6379,
                        "timeout": 0,
                        "database": 0
                    },
                    "validHandlers": {
                        "dummy": "CodeIgniter\\Cache\\Handlers\\DummyHandler",
                        "file": "CodeIgniter\\Cache\\Handlers\\FileHandler",
                        "memcached": "CodeIgniter\\Cache\\Handlers\\MemcachedHandler",
                        "predis": "CodeIgniter\\Cache\\Handlers\\PredisHandler",
                        "redis": "CodeIgniter\\Cache\\Handlers\\RedisHandler",
                        "wincache": "CodeIgniter\\Cache\\Handlers\\WincacheHandler"
                    }
                },
                false
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\codeigniter4\\framework\\system\\Boot.php",
            "line": 312,
            "function": "run",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->",
            "args": []
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\vendor\\codeigniter4\\framework\\system\\Boot.php",
            "line": 67,
            "function": "runCodeIgniter",
            "class": "CodeIgniter\\Boot",
            "type": "::",
            "args": [
                {}
            ]
        },
        {
            "file": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\index.php",
            "line": 56,
            "function": "bootWeb",
            "class": "CodeIgniter\\Boot",
            "type": "::",
            "args": [
                {
                    "systemDirectory": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Config/../../vendor/codeigniter4/framework/system",
                    "appDirectory": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Config/..",
                    "writableDirectory": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Config/../../writable",
                    "testsDirectory": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Config/../../tests",
                    "viewDirectory": "C:\\xampp\\htdocs\\absensi-sekolah-qr-code\\app\\Config/../Views"
                }
            ]
        }
    ]
}

**Comment by ikhsan3adi** [comment]
Extension `gd` belum terinstall

Mungkin ini bisa membantu [Tutorial mengkonfigurasi extension php](https://youtu.be/JtN7UwLkWFA)

**Comment by gustiagungmurahadi** [comment]
alhamdulillah sudah bisa bang tenkyu

**Comment by Eri31-lgtm** [comment]
> mau nanya min pas mau generate qr code stuck gak muncul qr code nya itu kenapa yaa yang jadi hanya file kosong
> 
> ![Screenshot 2024-07-10 212016](https://private-user-images.githubusercontent.com/122070997/347420718-80e35f28-64fb-41bc-bf42-66125be2fc8a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MTE1NzgsIm5iZiI6MTcyMDcxMTI3OCwicGF0aCI6Ii8xMjIwNzA5OTcvMzQ3NDIwNzE4LTgwZTM1ZjI4LTY0ZmItNDFiYy1iZjQyLTY2MTI1YmUyZmM4YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxNTIxMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGQxM2I4ZTM2N2IyZGUyMDdiNmIyNWE4ZjM4MzdhY2E5MzkyN2QwNjg2NzgzMTI5NjJiMDFmZWQxOGRlOGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OWg-5HH-Ym6tKtM8YqtNe3YOUn_YLJ-khJLlPF9p-Ow)

Ini hosting atau localhost ?
