### ISSUE TITLE
Generate QR Code nya gak jalan

### ISSUE THREAD

**Issue by Zaiful01** [ikhsan3adi/absensi-sekolah-qr-code#95]
Saat mau tekan generate QR Code gak jalan dan QR nya pun gak keluar pas di lihat aplikasi vscode

Tolong beri solusi min🙏

Terus min cara mengatasi 404-page not found pada controller or method is not found : generate::siswa

**Comment by ikhsan3adi** [comment]
Coba lihat #75

**Comment by ikhsan3adi** [comment]
Mungkin masalahnya sama seperti #89

**Comment by ikhsan3adi** [comment]
> Saat mau tekan generate QR Code gak jalan dan QR nya pun gak keluar pas di lihat aplikasi vscode
> 
> Tolong beri solusi min🙏
> 
> Terus min cara mengatasi 404-page not found pada controller or method is not found : generate::siswa

Coba jelaskan lebih detail dan berikan screenshot atau pesan eror
